name: First workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest]
        php-versions: ['7.2', '7.3', '7.4']


    name: ${{ matrix.os }} PHP ${{ matrix.php-versions }}
    steps:
      - uses: actions/checkout@v2

      - name: Hellow Codelies
        run: echo "Hellow from ${{ github.worflow }} triggerer by the ${{ github.event_name }} done by ${{ github.actor}}"
     
      - name: Greeting if windows
        if: matrix.os == 'windows-latest'
        run: echo "hey from wind2!"
      - name: Install infra dependencias
        run: |
          apt-get install mysql
          apt-get install php74
          apt-get install rabbitmq
      - name: ❤ More and More
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: |
            echo "Job context: $JOB_CONTEXT"
            echo "DONE workflow!"
      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
