name: First workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Hellow Codelies
        run: echo "Hellow from ${{ github.worflow }} triggerer by the ${{ github.event_name }} done by ${{ github.actor}}"
  