name: First workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hellow Codelies
        run: echo "Hellow from ${{ github.worflow }} triggerer by the ${{ github.event_name }} done by ${{ github.actor}}"

      - name: ❤ More and More
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: |
            echo "Job context: $JOB_CONTEXT"
            echo "DONE workflow!"
